const ExcelJS = require('exceljs');

/**
 * Utility to generate Excel reports using ExcelJS
 */
const generateExcelReport = async (res, title, columns, rows, userName) => {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet(title.substring(0, 31)); // excel sheet tab title length limit is 31
 
  // Brand header title blocks
  worksheet.mergeCells('A1:G1');
  const titleCell = worksheet.getCell('A1');
  titleCell.value = 'ALL 3D STUDIO';
  titleCell.font = { name: 'Arial', size: 16, bold: true, color: { argb: 'FF1E3A8A' } };
  titleCell.alignment = { vertical: 'middle', horizontal: 'center' };

  worksheet.mergeCells('A2:G2');
  const subCell = worksheet.getCell('A2');
  subCell.value = `${title} — Generated by ${userName} on ${new Date().toLocaleString()}`;
  subCell.font = { name: 'Arial', size: 10, italic: true, color: { argb: 'FF4B5563' } };
  subCell.alignment = { vertical: 'middle', horizontal: 'center' };

  // Blank row separator
  worksheet.addRow([]);

  // Configure table columns (starts at Row 4)
  worksheet.columns = columns.map((col) => ({
    header: col.header,
    key: col.key,
    width: col.width || 18,
  }));

  // Style the header row (Row 4)
  const headerRow = worksheet.getRow(4);
  headerRow.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFFFF' } };
  headerRow.height = 25;

  headerRow.eachCell((cell) => {
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF1E3A8A' }, // Primary navy theme
    };
    cell.alignment = { vertical: 'middle', horizontal: 'left', wrapText: true };
    cell.border = {
      top: { style: 'thin', color: { argb: 'FF9CA3AF' } },
      bottom: { style: 'medium', color: { argb: 'FF111827' } },
    };
  });

  // Populate data rows
  worksheet.addRows(rows);

  // Style the body rows (Row 5 onwards)
  worksheet.eachRow((row, rowNumber) => {
    if (rowNumber > 4) {
      row.height = 20;
      row.eachCell((cell) => {
        cell.font = { name: 'Arial', size: 9, color: { argb: 'FF374151' } };
        cell.alignment = { vertical: 'middle', horizontal: 'left' };
        cell.border = {
          bottom: { style: 'thin', color: { argb: 'FFE5E7EB' } },
        };
      });
    }
  });

  // Write Excel workbook straight to Express response stream
  await workbook.xlsx.write(res);
};

module.exports = {
  generateExcelReport,
};
