const PDFDocument = require('pdfkit');

/**
 * Utility to generate PDF reports using PDFKit
 */
const generatePDFReport = (res, title, headers, rows, userName) => {
  const doc = new PDFDocument({ margin: 30, size: 'A4', layout: 'landscape', bufferPages: true });

  // Pipe raw PDF stream directly to Express response
  doc.pipe(res);

  // Brand Header
  doc.fillColor('#1E3A8A').fontSize(22).text('ALL 3D STUDIO', { align: 'center', wordSpacing: 2 });
  doc.fillColor('#4B5563').fontSize(11).text('Work Management Platform — Enterprise Report', { align: 'center' });
  doc.moveDown(1);

  // Line separator
  doc.moveTo(30, doc.y).lineTo(810, doc.y).strokeColor('#E5E7EB').lineWidth(1).stroke();
  doc.moveDown(0.5);

  // Report Metadata Info
  doc.fillColor('#374151').fontSize(10);
  doc.text(`Report Title: ${title}`, 30, doc.y, { lineBreak: false });
  doc.text(`Generated By: ${userName}`, 400, doc.y, { align: 'right' });
  doc.moveDown(0.4);
  doc.text(`Generated On: ${new Date().toLocaleString()}`, 30, doc.y);
  doc.moveDown(1);

  // Summary Metrics Section
  doc.fillColor('#1F2937').fontSize(12).text(`Summary Metrics:`, { underline: true });
  doc.fontSize(10).text(`Total Records: ${rows.length}`);
  doc.moveDown(1);

  // Table Configuration
  let y = doc.y;
  const colWidth = 780 / headers.length; // landscape A4 printable width is 842 - 60 = 782

  // Table Headers
  doc.fillColor('#111827').fontSize(9).font('Helvetica-Bold');
  headers.forEach((header, index) => {
    doc.text(header, 30 + index * colWidth, y, { width: colWidth - 5, align: 'left' });
  });

  doc.moveDown(0.5);
  y = doc.y + 4;
  doc.moveTo(30, y).lineTo(810, y).strokeColor('#9CA3AF').lineWidth(1.5).stroke();
  y += 8;

  // Table Body Rows
  doc.font('Helvetica').fontSize(8).fillColor('#374151');
  rows.forEach((row) => {
    // Check if we need to add a new page (Landscape A4 height is 595, printable limit ~530)
    if (y > 520) {
      doc.addPage();
      y = 40; // reset y offset on new page

      // Repeat Table Headers on new page
      doc.fillColor('#111827').fontSize(9).font('Helvetica-Bold');
      headers.forEach((header, index) => {
        doc.text(header, 30 + index * colWidth, y, { width: colWidth - 5, align: 'left' });
      });
      y += 12;
      doc.moveTo(30, y).lineTo(810, y).strokeColor('#9CA3AF').lineWidth(1.5).stroke();
      y += 8;
      doc.font('Helvetica').fontSize(8).fillColor('#374151');
    }

    row.forEach((cell, index) => {
      const displayVal = cell === null || cell === undefined ? '-' : String(cell);
      doc.text(displayVal, 30 + index * colWidth, y, { width: colWidth - 5, align: 'left', lineBreak: false });
    });
    
    y += 18;
  });

  // Footer with Page Numbers (Buffer Pages makes it easy to compute total page count)
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(i);
    doc.moveTo(30, 560).lineTo(810, 560).strokeColor('#E5E7EB').lineWidth(0.5).stroke();
    doc.fillColor('#9CA3AF').fontSize(8).text(
      `Page ${i + 1} of ${range.count} | All 3D Studio Enterprise © ${new Date().getFullYear()}`,
      30,
      570,
      { align: 'center', width: 780 }
    );
  }

  doc.end();
};

module.exports = {
  generatePDFReport,
};
